# Generated by Django 3.1.7 on 2021-04-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
